### ISSUE TITLE
NEW version v0.4.1 cannot transfer

### ISSUE THREAD

**Issue by finexbit** [derogold/derogold#106]
Attempting to optimize your wallet to allow you to send large amounts at once.
This may take a very long time!
Do you want to proceed? (Y/n): y
Running optimization round 1...

Failed to send fusion transaction: An error occured whilst the daemon processed the request. Possibly our software is outdated, the daemon is faulty, or there is a programmer error. Check your daemon logs for more info. (set_log 4)
Failed to send fusion transaction: An error occured whilst the daemon processed the request. Possibly our software is outdated, the daemon is faulty, or there is a programmer error. Check your daemon logs for more info. (set_log 4)
Failed to send fusion transaction: An error occured whilst the daemon processed the request. Possibly our software is outdated, the daemon is faulty, or there is a programmer error. Check your daemon logs for more info. (set_log 4)
Failed to send fusion transaction: An error occured whilst the daemon processed the request. Possibly our software is outdated, the daemon is faulty, or there is a programmer error. Check your daemon logs for more info. (set_log 4)
Failed to send fusion transaction: An error occured whilst the daemon processed the request. Possibly our software is outdated, the daemon is faulty, or there is a programmer error. Check your daemon logs for more info. (set_log 4)

**Comment by LeoStehlik** [comment]
Can you please be more specific - the above log is not related to transfers, it’s related to sendFusionTransaction. Please specify the wallet version you use and which one (zedwallet-beta from the latest release?) Btw. as of the latest release, fusion transactions can only be done on zedwallet-beta / wallet-api and cost 10k dego per fusion transation. The functionality to optimize (sendFusionTransaction) was removed from zedwallet / derogold-service as of lastest release, large transactions automatically split into smaller ones not to exceed limits.

**Comment by finexbit** [comment]
zedwallet-beta from the latest release
new version zedwallet-beta  cannot transfer

Failed to send transaction: We were not able to submit our request to the daemon. Ensure it is online and not frozen.

**Comment by LeoStehlik** [comment]
could you please run `zedwallet-beta --log-level 4` and provide output, as well as log-level 4 from the daemon when attempting to send a transaction?

**Comment by finexbit** [comment]
and why every block so many small transfer
New transaction found!

Incoming transfer:
Hash: e1175c202ff3365348e054b7a74129ae888d439a444ffcc3de89fc73d9651743
Block height: 2344244
Timestamp: 2020-06-05 05:58
Amount: 0.03 DEGO


New transaction found!

Incoming transfer:
Hash: b67c66fcb5a5766bfe7f6eb587d82c162fae1fd21dac75756f8aea6b03ebb463
Block height: 2344244
Timestamp: 2020-06-05 05:58
Amount: 0.03 DEGO


New transaction found!

Incoming transfer:
Hash: fe38b54363ad7427407d094dc4d4edb9f3798aac92a123a00e574211536688a0
Block height: 2344244
Timestamp: 2020-06-05 05:58
Amount: 0.03 DEGO


New transaction found!

Incoming transfer:
Hash: af09a4c59e04c55a1326b16fd6566c7f3d71da764b87e803f83e4488cd06e539
Block height: 2344244
Timestamp: 2020-06-05 05:58
Amount: 0.04 DEGO


New transaction found!

Incoming transfer:
Hash: 90ff8b095ad455ece9759e4b57f21f0a04ad9fe10c4b6f74e90b17c2727217d4
Block height: 2344244
Timestamp: 2020-06-05 05:58
Amount: 0.04 DEGO


New transaction found!

Incoming transfer:
Hash: f24924754aa3cd0ed27a7271dbc63d0cf72984c97109dbb503ca9948c3d63958
Block height: 2344244
Timestamp: 2020-06-05 05:58
Amount: 0.04 DEGO


New transaction found!

Incoming transfer:
Hash: 3de6f01558bec26430241bfec4b66c15fc046734890522b8a27862d7740b2fec
Block height: 2344244
Timestamp: 2020-06-05 05:58
Amount: 0.06 DEGO


New transaction found!

Incoming transfer:
Hash: 20b17e49605cf89e4a494687eb3dddc421646a7288ebe17e5c64a880acf4bdc6
Block height: 2344244
Timestamp: 2020-06-05 05:58
Amount: 0.04 DEGO


New transaction found!

Incoming transfer:
Hash: 40b018544b7ac8598b8f622822d71a9fa428f34c3d19cb1638e56437c0d7b976
Block height: 2344244
Timestamp: 2020-06-05 05:58
Amount: 0.04 DEGO


New transaction found!

Incoming transfer:
Hash: fe9534869cdba0c8a095bad6536d58fa41f9f26beee40e345e4e18d1ac81c423
Block height: 2344244
Timestamp: 2020-06-05 05:58
Amount: 0.04 DEGO


New transaction found!

Incoming transfer:
Hash: 4a8640e33299308b9e1aad51233100a420dd99eb81a428418614102f69d93721
Block height: 2344244
Timestamp: 2020-06-05 05:58
Amount: 0.03 DEGO


New transaction found!

Incoming transfer:
Hash: f5c6d56e9b5d4ba9825f28803b9959ea77fc63272cedd0bb6567f85623b9cab0
Block height: 2344244
Timestamp: 2020-06-05 05:58
Amount: 0.03 DEGO

[18:19:30] [Info] [Sync] [Transactions]: Adding transaction: 54892e30932cb4acdc8c

**Comment by finexbit** [comment]
Is this correct? (Y/n): y
Confirm your password: ********[18:26:59] [Debug] [Sync] [Daemon]: Updating daemon info
**[18:27:00] [Debug] [Sync]: Approximate ram usage of stored blocks: 80.00 B, fetching more.
[18:27:00] [Debug] [Sync]: First checkpoint: 10be0cb5bdd6c5decc42d464d074a6194c0adace3cbae44e1e0f41baf3a38b5f
Last checkpoint: d505b3ebb1be737de184c9070daca9e7fb5ee6e022a7d548b4f48513ed38c6ed
[18:27:00] [Debug] [Sync] [Daemon]: Fetching blocks from the daemon

[18:27:09] [Debug] [Sync] [Daemon]: Updating daemon info
[18:27:10] [Debug] [Sync]: Approximate ram usage of stored blocks: 80.00 B, fetching more.
[18:27:10] [Debug] [Sync]: First checkpoint: 10be0cb5bdd6c5decc42d464d074a6194c0adace3cbae44e1e0f41baf3a38b5f
Last checkpoint: d505b3ebb1be737de184c9070daca9e7fb5ee6e022a7d548b4f48513ed38c6ed
[18:27:10] [Debug] [Sync] [Daemon]: Fetching blocks from the daemon



Failed to send transaction: We were not able to submit our request to the daemon. Ensure it is online and not frozen.
[DEGO fb777]: [18:28:10] [Debug] [Sync]: Approximate ram usage of stored blocks: 80.00 B, fetching more.
[18:28:10] [Debug] [Sync]: First checkpoint: 10be0cb5bdd6c5decc42d464d074a6194c0adace3cbae44e1e0f41baf3a38b5f
Last checkpoint: d505b3ebb1be737de184c9070daca9e7fb5ee6e022a7d548b4f48513ed38c6ed
[18:28:10] [Debug] [Sync] [Daemon]: Fetching blocks from the daemon
[18:28:11] [Debug] [Sync] [Daemon]: Updating daemon info

**Comment by LeoStehlik** [comment]
> and why every block so many small transfer
> New transaction found!
> 

someone is spamming your wallet with 0.03 DEGO transfers

**Comment by LeoStehlik** [comment]
> Failed to send transaction: We were not able to submit our request to the daemon. Ensure it is online and not frozen.

are there any details on the daemon side log (set_log 4)? could you try to open the zedwallet-beta against one of our remote public daemons ? 

I am unable to recreate your problem - the problem might be either communication with your local daemon or on the wallet side (did you try to resync the wallet from scratch?)

**Comment by finexbit** [comment]
cannot connect to remote public daemons
set_log 4, log is at above
all communication with your local daemon is success, only transfer have issue
already resync , get lastest block

**Comment by LeoStehlik** [comment]
can you be specific on “transfer have issues” please? we noticed transferrring large amounts can take up to 48 hour to complete, depending on a] fragmentation of the inputs b] amount being sent

**Comment by LeoStehlik** [comment]
closing as the user did not follow up.
