### ISSUE TITLE
v0.4.2.2 still have the same transfer issue, cannot transfer

### ISSUE THREAD

**Issue by finexbit** [derogold/derogold#108]
[DEGO fb777]: 17
Attempting to optimize your wallet to allow you to send large amounts at once.
This may take a very long time!
Do you want to proceed? (Y/n): y
Running optimization round 1...

Failed to send fusion transaction: An error occured whilst the daemon processed the request. Possibly our software is outdated, the daemon is faulty, or there is a programmer error. Check your daemon logs for more info. (set_log 4)
Failed to send fusion transaction: An error occured whilst the daemon processed the request. Possibly our software is outdated, the daemon is faulty, or there is a programmer error. Check your daemon logs for more info. (set_log 4)
Failed to send fusion transaction: An error occured whilst the daemon processed the request. Possibly our software is outdated, the daemon is faulty, or there is a programmer error. Check your daemon logs for more info. (set_log 4)
Failed to send fusion transaction: An error occured whilst the daemon processed the request. Possibly our software is outdated, the daemon is faulty, or there is a programmer error. Check your daemon logs for more info. (set_log 4)
Optimization complete!
[DEGO fb777]: 7
Note: You can type cancel at any time to cancel the transaction

What address do you want to transfer to?: dg4xJSKP2c7MkHY2oTzfPxC2VrQW6Et3zRnePK88rytzEJu3xFByHntgqYPKivHd3CSSEY1ZKhaufGqY7Q7yWh3K1fkgVygGp

What payment ID do you want to use?
These are usually used for sending to exchanges.
Warning: If you were given a payment ID,
you MUST use it, or your funds may be lost!
Hit enter for the default of no payment ID: 

How much DEGO do you want to send?: 2139900000

Confirm Transaction?
You are sending 2,139,900,000.00 DEGO, with a network fee of 10,000.00 DEGO,
and a node fee of 0.00 DEGO.

FROM: fb777
TO: dg4xJSKP2c7MkHY2oTzfPxC2VrQW6Et3zRnePK88rytzEJu3xFByHntgqYPKivHd3CSSEY1ZKhaufGqY7Q7yWh3K1fkgVygGp

Is this correct? (Y/n): y
Confirm your password: **********
Failed to send transaction: We were not able to submit our request to the daemon. Ensure it is online and not frozen.

**Comment by Zzzttfx** [comment]
have you try use remote node? Try one 
dego.bot.tips:80
dego.bot.tips:433
derogold4ever.online:6969
publicnode.ydns.eu:6969
degonode.ydns.eu:6969
If still doesn't work, try change another node

**Comment by finexbit** [comment]
remote node have the same issue
Is this correct? (Y/n): y
Confirm your password: **********
Failed to send transaction: We were not able to submit our request to the daemon. Ensure it is online and not frozen.

**Comment by Zzzttfx** [comment]
maybe need to wait until next fork.

**Comment by LeoStehlik** [comment]
the correct procedure is 1. rescan wallet 2. optimize wallet 3. transfer. If you have spammed wallet with huge number of small inputs (0,01 DEGO), optimize wallet multiple times. Best to wait past the fork height to reduce fusion fees. The dego dev team cannot recreate the issue, therefore we do not consider this as a problem in the code, likely a user-related issue. Therefore, we believe the above procedure will most likely resolve your issue.

**Comment by LeoStehlik** [comment]
closing the issue as procedure for user-related setup has been provided.
