### ISSUE TITLE
Discord Crashed

### ISSUE THREAD

**Issue by dagwood-Fenichuck** [derogold/derogold#113]
Hello Discord has crashed and need an answer now,  how to connect explorer what programs do i need to run please to make it work cant find any docs about it

**Comment by LeoStehlik** [comment]
Sorry mate, if Discord crashed, you better open an issue with Discord, not with DeroGold! :-) If you need answers now, sorry, you’re on your own. The code is pretty explanatory and anyone can learn over time how to use it. We are not here to spoon-feed anyone who “wants it all and wants it now”.

**Comment by LeoStehlik** [comment]
Closing the issue as it is not relevant to DeroGold.

**Comment by dagwood-Fenichuck** [comment]
My apologise Leo it sounded bombastic  it should have read Discord has crashed and  need an answer before i can go further,  Now how do i connect etc etc?    i dont need spoon feeding but a little help and pointing in the right direction would have been a great gesture towards someone who is trying to learn  sir.
