### ISSUE TITLE
Got error  zedwallet open the wallet file

### ISSUE THREAD

**Issue by finexbit** [derogold/derogold#33]
Finished scanning blockchain!
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Abortedls

Got error  zedwallet open the wallet file

**Comment by rogerrobers** [comment]
Try to rescan the wallet and see

**Comment by finexbit** [comment]
it is cannot open the wallet, reinit need a lot of time

**Comment by LeoStehlik** [comment]
@rogerrobers did @finexbit followed up on this at all, I see not much relevant information here. can we close this?

**Comment by rogerrobers** [comment]
closing the issue
