### ISSUE TITLE
Still syning here is the log file

### ISSUE THREAD

**Issue by cchalifo999** [derogold/derogold#37]
### System Information
server 2016 
9gb ram 

**Operating System**: 
**OS Version**: 
**CPU Make, Model, & Speed**: 
**Amount of RAM**: 
**Hard Drive Type**: 
**Hard Drive Size**: 
**Volume Type**: 

### TurtleCoin Build Information

**Version:** 
**Binary Source:** 
**If self compiled, please provide all the build commands you used**
```
Please insert your build commands here. Example:

mkdir build && cd build
cmake .. -DBOOST_ROOT=/home/turtlecoin/boost_1_59_0
make -j4
```

**If self compiled, please provide of your TurtleCoin CMake output at the default verbosity**:
```
Please insert your default verbosity CMake output here
```

### Issue Report

**Binary Reported:** 

#### Steps to Reproduce

1. 
2. 
3. 
4.

**Comment by cchalifo999** [comment]
[DeroGoldd.log](https://github.com/derogold/derogold/files/3273638/DeroGoldd.log)
and the release version is DeroGold v0.1.0.12

**Comment by LeoStehlik** [comment]
One clarifying question, what is the storage media in your machine, is it SSD or spinning HDD? 

Since your machine has 9GB of memory, we suggest to start the DeroGoldd daemon with the following parameters:

DeroGoldd --add-peer publicnode.ydns.eu --db-max-open-files 700 --db-read-buffer-size 1024 --db-write-buffer-size 1024 --db-threads 10

The --add-peer adds DeroGold fast HW node for faster sync, the other parameters optimize how the daemon communicates with the rocksdb database.

**Comment by cchalifo999** [comment]
> 
> 
> One clarifying question, what is the storage media in your machine, is it SSD or spinning HDD?
> 
> Since your machine has 9GB of memory, we suggest to start the DeroGoldd daemon with the following parameters:
> 
> DeroGoldd --add-peer publicnode.ydns.eu --db-max-open-files 700 --db-read-buffer-size 1024 --db-write-buffer-size 1024 --db-threads 10
> 
> The --add-peer adds DeroGold fast HW node for faster sync, the other parameters optimize how the daemon communicates with the rocksdb database.

esxi  hd
and can i add thoes permint in the config file

**Comment by cchalifo999** [comment]
if i had other nodes tat are haveing truble with syncing the blockchah will that help 2

**Comment by LeoStehlik** [comment]
yes, it will help too, assuming you have enough RAM on the other nodes.

**Comment by cchalifo999** [comment]
i restarde the deamond i'll lett you know if it works

**Comment by cchalifo999** [comment]
@LeoStehlik  ty for you help it seames to be working right

**Comment by LeoStehlik** [comment]
while syncing also disable all incomming p2p and rpc connections:
--p2p-bind 127.0.0.1 --rpc-bind 127.0.0.1 

for the sync on your 9GB machine, you can also increase the db read/write values (both) to 2048.
