### ISSUE TITLE
--db-max-open-files issue with DEGO

### ISSUE THREAD

**Issue by wrkzdev** [derogold/derogold#53]
Some investigation of RPC issues and number of open file limit by DEGO and comparing to other daemons with my server:
* DEGO: Currently openning > 600 of sst files. How to check it? `ls -l datadir/DB|grep sst | wc -l` and also `/proc/PID/fd` (example `ls -l /proc/18014/fd`)
* TRTL: (My testing environment OUTDATED ~~https://github.com/wrkzcoin/turtlecoin_rnd/tree/development~~) ~ 200 sst files more or less. 
* WRKZ: (My testing environment also from OUTDATED ~~https://github.com/wrkzcoin/wrkzcoin/tree/dev~~) 1 sst file.

If we run with default max open file which is 500, default slowly respond to RPC. I made another test by `--db-max-open-files=-1`, DEGO response more faster and keep responding.

However, 500 open files is huge. I propose some copy / paste setting from WRKZ in this PR:
https://github.com/derogold/derogold/pull/52

@LeoStehlik please review :)

**Comment by LeoStehlik** [comment]
so for the upcoming release I plan to change: db read cache 256, db write cache 512, db threads 4 and db max open files -1 for the system to manage it within its set limits.

**Comment by LeoStehlik** [comment]
as per above, changes done for the latest release (0.3.1.1), closing
